use_frameworks!
platform :ios, "9.2"
#platform :ios
pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'
pod 'AFNetworking'
#pod "DownloadButton"
#pod 'OpenCV' '2.4.9'
pod 'OpenCV'
pod 'QBImagePickerController'
pod 'MBCircularProgressBar'
pod 'SwiftyDropbox', '~> 3.0.0'

#use_frameworks!

#target 'LEDSignalDetector' do
#	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#end

